language: python
python:
  - "3.6"
  - "nightly"
install:
  - pip install cython
  - pip install scipy
  - pip install scikit-learn
  - pip install matplotlib
script:
  - python setup.py build_ext --inplace
  - pytest
