language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip freeze
script:
  - python setup.py build_ext --inplace
  - pytest
before_install:	
  - pip install codecov
env:
  - CODECOV_TOKEN=d8f839b7-cf16-4d43-83c7-9d595f6e1d44
after_success:
  - codecov
