language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip freeze
script:
  - python setup.py build_ext --inplace
  - pytest
before_install:	
  - pip install codecov
after_success:
  - codecov
