language: python
python:
  - "3.6"
before_install:
  - pip install pytest pytest-cov codecov
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest
  - pip freeze
script:
  - python setup.py build_ext --inplace --define CYTHON_TRACE
  - pytest --cov-report term --cov=harmonic --cov-config=.coveragerc
after_success:
  - codecov --token d8f839b7-cf16-4d43-83c7-9d595f6e1d44
  - cd docs && make html
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/_build/html
  committer-from-gh: false
