name: Harmonic

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        bash getting_started.sh       
    
    - name: Install harmonic
      run: |
        python setup.py build_ext --inplace --define CYTHON_TRACE
        pytest --cov-report term --cov=harmonic --cov-config=.coveragerc 
        codecov --token d8f839b7-cf16-4d43-83c7-9d595f6e1d44
    
    - name: Build Documentation
      run: |
        cd docs && make html